/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/Dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/detailed_section/apartadoDetallado_estudiante`; params?: Router.UnknownInputParams; } | { pathname: `/detailed_section/apartadoDetallado_oferta`; params?: Router.UnknownInputParams; } | { pathname: `/Home/Estadisticas`; params?: Router.UnknownInputParams; } | { pathname: `/Home/Inicio`; params?: Router.UnknownInputParams; } | { pathname: `/Home/privacy`; params?: Router.UnknownInputParams; } | { pathname: `/Home/terms`; params?: Router.UnknownInputParams; } | { pathname: `/main_section/apartadoJovenes`; params?: Router.UnknownInputParams; } | { pathname: `/main_section/apartadoOfertas`; params?: Router.UnknownInputParams; } | { pathname: `/registration_section/editarPerfil`; params?: Router.UnknownInputParams; } | { pathname: `/registration_section/profileViewer`; params?: Router.UnknownInputParams; } | { pathname: `/registration_section/registraroferta`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard/Dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/detailed_section/apartadoDetallado_estudiante`; params?: Router.UnknownOutputParams; } | { pathname: `/detailed_section/apartadoDetallado_oferta`; params?: Router.UnknownOutputParams; } | { pathname: `/Home/Estadisticas`; params?: Router.UnknownOutputParams; } | { pathname: `/Home/Inicio`; params?: Router.UnknownOutputParams; } | { pathname: `/Home/privacy`; params?: Router.UnknownOutputParams; } | { pathname: `/Home/terms`; params?: Router.UnknownOutputParams; } | { pathname: `/main_section/apartadoJovenes`; params?: Router.UnknownOutputParams; } | { pathname: `/main_section/apartadoOfertas`; params?: Router.UnknownOutputParams; } | { pathname: `/registration_section/editarPerfil`; params?: Router.UnknownOutputParams; } | { pathname: `/registration_section/profileViewer`; params?: Router.UnknownOutputParams; } | { pathname: `/registration_section/registraroferta`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/dashboard/Dashboard${`?${string}` | `#${string}` | ''}` | `/detailed_section/apartadoDetallado_estudiante${`?${string}` | `#${string}` | ''}` | `/detailed_section/apartadoDetallado_oferta${`?${string}` | `#${string}` | ''}` | `/Home/Estadisticas${`?${string}` | `#${string}` | ''}` | `/Home/Inicio${`?${string}` | `#${string}` | ''}` | `/Home/privacy${`?${string}` | `#${string}` | ''}` | `/Home/terms${`?${string}` | `#${string}` | ''}` | `/main_section/apartadoJovenes${`?${string}` | `#${string}` | ''}` | `/main_section/apartadoOfertas${`?${string}` | `#${string}` | ''}` | `/registration_section/editarPerfil${`?${string}` | `#${string}` | ''}` | `/registration_section/profileViewer${`?${string}` | `#${string}` | ''}` | `/registration_section/registraroferta${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/Dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/detailed_section/apartadoDetallado_estudiante`; params?: Router.UnknownInputParams; } | { pathname: `/detailed_section/apartadoDetallado_oferta`; params?: Router.UnknownInputParams; } | { pathname: `/Home/Estadisticas`; params?: Router.UnknownInputParams; } | { pathname: `/Home/Inicio`; params?: Router.UnknownInputParams; } | { pathname: `/Home/privacy`; params?: Router.UnknownInputParams; } | { pathname: `/Home/terms`; params?: Router.UnknownInputParams; } | { pathname: `/main_section/apartadoJovenes`; params?: Router.UnknownInputParams; } | { pathname: `/main_section/apartadoOfertas`; params?: Router.UnknownInputParams; } | { pathname: `/registration_section/editarPerfil`; params?: Router.UnknownInputParams; } | { pathname: `/registration_section/profileViewer`; params?: Router.UnknownInputParams; } | { pathname: `/registration_section/registraroferta`; params?: Router.UnknownInputParams; };
    }
  }
}
